name: validomix
description: From Strings to Objects Validomix validates all
version: 1.0.0
repository: https://github.com/flarebyte/validomix

environment:
  sdk: ^3.1.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
