name: validomix
description: From Strings to Objects Validomix validates all
version: 0.3.0
repository: https://github.com/flarebyte/validomix

environment:
  sdk: ^3.4.3

dependencies:
  eagleyeix:
    git:
      url: https://github.com/flarebyte/eagleyeix.git
      ref: v0.3.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.21.0
